name: "Publish Docker image"

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: DeterminateSystems/nix-installer-action@v11
      - uses: DeterminateSystems/magic-nix-cache-action@v6
      - run: nix flake check
      - run: nix build .\#docker-image

      - name: Push docker image to ghcr.io
        run: |
          IMG_ID=$(docker load -i result | sed -nr 's/^Loaded image: (.*)$/\1/p' | xargs -I{} docker image ls "{}" --format="{{.ID}}")
          echo "Tagging $IMG_ID"
          docker tag $IMG_ID ghcr.io/ocramius/oci-srm-server-mock-rust:${{ github.event.release.tag_name }}
          docker push ghcr.io/ocramius/oci-srm-server-mock-rust:${{ github.event.release.tag_name }}
