name: "Publish Docker image"

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: docker/login-action@abd2ef45e78c5afb21d64d4ca52ee8550d9572c7 # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
      - uses: DeterminateSystems/magic-nix-cache-action@908b263ff629f4cc17666315b7fd3ec127c6244d # v14
      - run: nix flake check
      - run: nix build .\#docker-image

      - name: Push docker image to ghcr.io
        run: |
          IMG_ID=$(docker load -i result | sed -nr 's/^Loaded image: (.*)$/\1/p' | xargs -I{} docker image ls "{}" --format="{{.ID}}")
          echo "Tagging $IMG_ID"
          docker tag $IMG_ID ghcr.io/ocramius/oci-srm-server-mock-rust:${{ github.event.release.tag_name }}
          docker push ghcr.io/ocramius/oci-srm-server-mock-rust:${{ github.event.release.tag_name }}
